apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      releaseName: prometheus-argocd
      valueFiles:
      - $values/values.yaml
  - repoURL: 'https://github.com/silveraignacio/argocd-demo.git'
    path: prometheus
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
