apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat
  namespace: default
spec:
  syncPolicy:
    automated: {}
  project: default
  source:
    chart: tomcat
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.5.14
    helm:
      releaseName: tomcat
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd